---
- hosts: all

  tasks:
    - apt: name={{ item }} state=latest
      become: yes
      with_items:
        - ack-grep
        - clang-format-3.6
        - clang-3.6
        - llvm
        - exuberant-ctags
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - flex
      when: ansible_distribution == 'Ubuntu'
      tags: always

    - easy_install: name=pip
      become: yes
      tags: always
