---
- hosts: all
  tasks:
    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - vimrc

    - file: path=~/.config/nvim/{{ item }} state=directory recurse=Yes
      with_items:
        - autoload

    - file: src={{ curdir }}/files/vimrc dest=~/.config/nvim/init.vim state=link

    - pip: name=neovim state=latest
      become: yes

    - get_url:
        dest: ~/.config/nvim/autoload/plug.vim
        url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'


    - file: path=~/.vim/spell state=directory

    - command: nvim -i NONE -c PlugUpdate -c quitall
